### ISSUE TITLE
Can not build the FPTaylor on ubuntu 16.04

### ISSUE THREAD

**Issue by yuanshuoastro** [soarlab/FPTaylor#13]
`
ubuntu@test-1:~/FPTaylor⟫ make

cd INTERVAL; make
make[1]: Entering directory '/home/ubuntu/FPTaylor/INTERVAL'
make[1]: Leaving directory '/home/ubuntu/FPTaylor/INTERVAL'
ocamlc -c -I INTERVAL version.mli
ocamlc -c -I INTERVAL version.ml
ocamlc -c -I INTERVAL lib.mli
ocamlc -c -I INTERVAL lib.ml
File "lib.ml", line 198, characters 2-27:
Error: Unbound value Format.pp_flush_formatter
Makefile:148: recipe for target 'lib.cmo' failed
make: *** [lib.cmo] Error 2
2 ubuntu@test-1:~/FPTaylor⟫ 
`

Could you help me? 
Thank you very much!

**Comment by keram88** [comment]
FPTaylor should build on Ubuntu 14.04. I'm sorry for having previously given you incorrect information. I'm closing this issue, but feel free to reopen the issue if you experience problems on 14.04.

**Comment by monadius** [comment]
FPTaylor should work on Ubuntu 16.04. I am fixing the issue now.

**Comment by monadius** [comment]
The issue is fixed. Please pull the latest commit and try to build again.

**Comment by yuanshuoastro** [comment]
Thank you @monadius  and @keram88 !
