### ISSUE TITLE
Does not build with ocamlc >= 4.06

### ISSUE THREAD

**Issue by sampollard** [soarlab/FPTaylor#29]
If you compile with e.g. ocamlc 4.06 you get a bunch of warnings like this:

```
If you need to stay compatible with OCaml < 4.07, you can use the 
stdlib-shims library: https://github.com/ocaml/stdlib-shims
```
Then an error:
```
ocamlc -c -I b_and_b -I INTERVAL more_num.mli
File "more_num.mli", line 13, characters 16-23:
13 | val numerator : Num.num -> Big_int.big_int
                     ^^^^^^^
Error: Unbound module Num
make: *** [Makefile:183: more_num.cmi] Error 2
```

I got around this by doing `ocaml switch create 4.05.0`, which then built successfully. You may want to update the README.md. This was on Ubuntu 20.04.

**Comment by monadius** [comment]
Another way to solve your compilation issue is to install the legacy `Num` library for OCaml 4.06: `opam install num`. I will update the Readme file with this info.

I don't get any warnings about Stdlib on macOS with OCaml 4.06.1 and OCaml 4.07.1. I am going to test FPTaylor on Ubuntu and decide the best course of action: require `stdlib-shims` for OCaml < 4.07 or update the minimal required OCaml version to 4.07.
